<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\API\LexiLink.API\LexiLink.API.csproj" />
    <ProjectReference Include="..\..\Common\Domain\LexiLink.Common.Domain.csproj" />
    <ProjectReference Include="..\..\Common\Application\LexiLink.Common.Application.csproj" />
    <ProjectReference Include="..\..\Common\Infrastructure\LexiLink.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Games\Domain\LexiLink.Modules.Games.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Games\IntegrationEvents\LexiLink.Modules.Games.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Modules\Games\Application\LexiLink.Modules.Games.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Games\Infrastructure\LexiLink.Modules.Games.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Players\Domain\LexiLink.Modules.Players.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Players\IntegrationEvents\LexiLink.Modules.Players.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Modules\Players\Application\LexiLink.Modules.Players.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Players\Infrastructure\LexiLink.Modules.Players.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Stats\Application\LexiLink.Modules.Stats.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Stats\Infrastructure\LexiLink.Modules.Stats.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Energy\Domain\LexiLink.Modules.Energy.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Energy\Application\LexiLink.Modules.Energy.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Energy\Infrastructure\LexiLink.Modules.Energy.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Quests\Domain\LexiLink.Modules.Quests.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Quests\IntegrationEvents\LexiLink.Modules.Quests.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Modules\Quests\Application\LexiLink.Modules.Quests.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Quests\Infrastructure\LexiLink.Modules.Quests.Infrastructure.csproj" />
  </ItemGroup>

</Project>
