name: lexilink_app
description: LexiLink cross-platform Flutter client.
publish_to: none

version: 1.0.0+7

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.1.0
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^16.2.5
  google_mobile_ads: ^5.1.0
  http: ^1.6.0
  in_app_purchase: ^3.2.3
  intl: any
  shared_preferences: ^2.5.5
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.2
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/sfx/
    - assets/audio/music/
