name: lexilink_app
description: LexiLink cross-platform Flutter client.
publish_to: none

version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.2.5
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
