<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LexiLink.Modules.Undo.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\LexiLink.Modules.Undo.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Application\LexiLink.Common.Application.csproj" />
    <ProjectReference Include="..\..\Players\IntegrationEvents\LexiLink.Modules.Players.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Quests\IntegrationEvents\LexiLink.Modules.Quests.IntegrationEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
