<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>LexiLink.DatabaseMigrator</RootNamespace>
    <AssemblyName>LexiLink.DatabaseMigrator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

</Project>
