<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LexiLink.Modules.Payments.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\LexiLink.Modules.Payments.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Application\LexiLink.Common.Application.csproj" />
    <ProjectReference Include="..\..\Diamond\Application\LexiLink.Modules.Diamond.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
